
GET http://localhost:8083/operation/extra/info
Accept: application/json
Cache-Customer: dummy
Cache-Store: mongo

###
POST http://localhost:8083/operation/list
Content-Type: application/json
Cache-Customer: dummy
Cache-Store: mongo

{
  "limit": 3,
  "sortBy": "CREATED_DTM",
  "sortDirection": "ASC"
}

###
PUT http://localhost:8083/operation/batch
Content-Type: application/json
Cache-Customer: dummy
Cache-Store: mongo

{
  "data": [
    {
      "uid": null,
      "createdDtm": null,
      "updatedDtm": null,
      "ttlEffectedDtm": null,
      "data": {
        "description": "I am dummy mongo1.",
        "name": "This is my new name1!"
      },
      "ttlSec": null
    },
    {
      "uid": null,
      "createdDtm": null,
      "updatedDtm": null,
      "ttlEffectedDtm": null,
      "data": {
        "description": "I am dummy mongo2.",
        "name": "This is my new name2!"
      },
      "ttlSec": null
    }
  ]
}

###
POST http://localhost:8083/operation/batch
Content-Type: application/json
Cache-Customer: dummy
Cache-Store: mongo

{
  "data": [
    {
      "uid": null,
      "createdDtm": null,
      "updatedDtm": null,
      "ttlEffectedDtm": null,
      "data": {
        "description": "I am dummy mongo1.",
        "name": "This is my name1!"
      },
      "ttlSec": null
    },
    {
      "uid": null,
      "createdDtm": null,
      "updatedDtm": null,
      "ttlEffectedDtm": null,
      "data": {
        "description": "I am dummy mongo2.",
        "name": "This is my name2!"
      },
      "ttlSec": null
    }
  ]
}

###
PUT http://localhost:8083/operation
Content-Type: application/json
Cache-Customer: dummy
Cache-Store: mongo

{
  "uid": null,
  "createdDtm": null,
  "updatedDtm": null,
  "ttlEffectedDtm": null,
  "data": {
    "description": "I am dummy mongo.",
    "name": "This is my new name!"
  },
  "ttlSec": null
}

###
DELETE http://localhost:8083/operation/{uid}
Accept: application/json
Cache-Customer: dummy
Cache-Store: mongo

###
GET http://localhost:8083/operation/{uid}
Accept: application/json
Cache-Customer: dummy
Cache-Store: mongo

###

###
POST http://localhost:8083/operation
Content-Type: application/json
Cache-Customer: dummy
Cache-Store: mongo

{
  "uid": null,
  "createdDtm": null,
  "updatedDtm": null,
  "ttlEffectedDtm": null,
  "data": {
    "description": "I am dummy mongo.",
    "name": "This is my name!"
  },
  "ttlSec": null
}
